apiVersion: apps/v1
kind: Deployment
metadata:
  name: architect-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: architect
  template:
    metadata:
      labels:
        app: architect
    spec:
      containers:
        - name: architect-container
          image: registry.digitalocean.com/ungate/architect-ungate:development
          ports:
            - containerPort: 3000
          resources:
            limits:
              memory: "1.5Gi"
              cpu: "1"
            requests:
              memory: "768Mi"
              cpu: "500m"
          imagePullPolicy: Always
      imagePullSecrets:
        - name: docker-secret
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 1
      maxSurge: 1