apiVersion: apps/v1
kind: Deployment
metadata:
  name: architect-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: architect
  template:
    metadata:
      labels:
        app: architect
    spec:
      containers:
        - name: architect-container
          image: registry.digitalocean.com/ungate/mematrix-architect:development
          ports:
            - containerPort: 3000
          resources:
            limits:
              memory: "1.5Gi"
              cpu: "1"
            requests:
              memory: "768Mi"
              cpu: "500m"
          volumeMounts:
            - name: character-config
              mountPath: /app/characters/architect.json
              subPath: architect.json
            - name: character-config
              mountPath: /app/.env
              subPath: .env
          args: ["pnpm","start", "--characters=/app/characters/architect.json", ""]
          imagePullPolicy: Always
      imagePullSecrets:
        - name: docker-secret
      volumes:
        - name: character-config
          configMap:
            name: architect
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 1
      maxSurge: 1