packages:
    - "docs"
    - "packages/adapter-sqlite"
    - "packages/client-twitter"
    - "packages/plugin-image-generation"
    - "packages/core"
    - "packages/client-direct"
    - "packages/plugin-node"
    - "web-agent"
    - "agent"
