apiVersion: v1
kind: Service
metadata:
  name: architect-service
spec:
  selector:
    app: architect
  ports:
    - name: http
      protocol: TCP
      port: 3000
      targetPort: 3000
  type: ClusterIP